export const RECEIVE_APARTMENTS_LIST = 'RECEIVE_APARTMENTS_LIST';
export const REQUEST_APARTMENTS_LIST = 'REQUEST_APARTMENTS_LIST';
export const RECEIVE_APARTMENT = 'RECEIVE_APARTMENT';
export const REQUEST_APARTMENT = 'REQUEST_APARTMENT';
